/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alumno
 */
public class ConvertirDiv extends javax.swing.JFrame {

    /**
     * Creates new form ConvertirDiv
     */
    public ConvertirDiv() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TipoDiv1 = new javax.swing.JComboBox<>();
        TipoDiv2 = new javax.swing.JComboBox<>();
        ConvertirDiv = new javax.swing.JButton();
        CantidadDiv = new javax.swing.JTextField();
        DivisaFinal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de divisas");

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 3, 14)); // NOI18N
        jLabel1.setText("Intruduce Importe:");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 3, 14)); // NOI18N
        jLabel2.setText("Convertir a:");

        TipoDiv1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GTQ", "USD", "EUR", "PESO MX" }));
        TipoDiv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDiv1ActionPerformed(evt);
            }
        });

        TipoDiv2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GTQ", "USD", "EUR", "PESO MX" }));
        TipoDiv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDiv2ActionPerformed(evt);
            }
        });

        ConvertirDiv.setFont(new java.awt.Font("Microsoft YaHei", 3, 12)); // NOI18N
        ConvertirDiv.setText("Convertir");
        ConvertirDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertirDivActionPerformed(evt);
            }
        });

        DivisaFinal.setFont(new java.awt.Font("Berlin Sans FB Demi", 3, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DivisaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CantidadDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TipoDiv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(TipoDiv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addComponent(ConvertirDiv))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoDiv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CantidadDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(TipoDiv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ConvertirDiv))
                .addGap(39, 39, 39)
                .addComponent(DivisaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Double ValorDiv1=0.0;
    Double ValorDiv2=0.0;
    String TipoDi1 = "GTQ";
    String TipoDi2 = "GTQ";
    private void ConvertirDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertirDivActionPerformed
       
        ValorDiv1 = Double.parseDouble(CantidadDiv.getText());
        String DivisaSelc = "  ";
        DivisaSelc=DivisaSelc+TipoDiv2.getSelectedItem().toString();
        //Mostrar la convercion
        OperacionesConv();
        DivisaFinal.setText("Resultado: "+ValorDiv2 +DivisaSelc);
        
    }//GEN-LAST:event_ConvertirDivActionPerformed

    private void TipoDiv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDiv1ActionPerformed
        TipoDi1=TipoDiv1.getSelectedItem().toString();
        OperacionesConv();
    }//GEN-LAST:event_TipoDiv1ActionPerformed

    private void TipoDiv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDiv2ActionPerformed
         TipoDi2=TipoDiv2.getSelectedItem().toString();
    }//GEN-LAST:event_TipoDiv2ActionPerformed
    public void OperacionesConv(){
switch(TipoDi1)
    {
        case "GTQ":
        {
            if(TipoDi2.equals("USD"))
            {
                ValorDiv2 = ValorDiv1*0.13;
            }
            else if (TipoDi2.equals("EUR"))
            {
                ValorDiv2 = ValorDiv1*0.12;
            }
            else if (TipoDi2.equals("PESO MX"))
            {
                ValorDiv2 = ValorDiv1*2.63;
            }
            else
            {
                ValorDiv2 = ValorDiv1;
            }
            break;
        }
        case "USD":
        {
            if(TipoDi2.equals("GTQ"))
            {
                ValorDiv2 = ValorDiv1*7.67;
            }
            else if (TipoDi2.equals("EUR"))
            {
                ValorDiv2 = ValorDiv1*0.95;
            }
            else if (TipoDi2.equals("PESO MX"))
            {
                ValorDiv2 = ValorDiv1*20.18;
            }
            else
            {
                ValorDiv2 = ValorDiv1;
            }
            break;
        }
        case "EUR":
        {
            if(TipoDi2.equals("USD"))
            {
                ValorDiv2 = ValorDiv1*1.05;
            }
            else if (TipoDi2.equals("GTQ"))
            {
                ValorDiv2 = ValorDiv1*8.08;
            }
            else if (TipoDi2.equals("PESO MX"))
            {
               ValorDiv2 = ValorDiv1*21.26;
            }
            else
            {
               ValorDiv2 = ValorDiv1;
            }
            break;
        }
        case "PESO MX":
        {
            if(TipoDi2.equals("USD"))
            {
                ValorDiv2 = ValorDiv1*0.050;
            }
            else if (TipoDi2.equals("GTQ"))
            {
                ValorDiv2 = ValorDiv1*0.38;
            }
            else if (TipoDi2.equals("EUR"))
            {
                ValorDiv2 = ValorDiv1*0.047;
            }
            else
            {
                ValorDiv2 = ValorDiv1;
            }
            break;
        }
}
    }    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvertirDiv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvertirDiv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvertirDiv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvertirDiv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvertirDiv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CantidadDiv;
    private javax.swing.JButton ConvertirDiv;
    private javax.swing.JLabel DivisaFinal;
    private javax.swing.JComboBox<String> TipoDiv1;
    private javax.swing.JComboBox<String> TipoDiv2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
